# Generated by Django 4.2.20 on 2025-03-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('calories', models.IntegerField()),
                ('km_walked', models.IntegerField()),
                ('hours_slept', models.FloatField()),
            ],
        ),
    ]
